### ISSUE TITLE
Suggestion: Please use the reflectable package for reflection capabilities 

### ISSUE THREAD

**Issue by bjesuiter** [stevenroose/dart-enums#1]
I would like to use your enums package. Because even though enums are avaliable in the language now, their capabilities are really limited. 

But the use of reflection is not good for transpiled dart2js, because of it's overhead and beta stadium of dart2js mirrors support. 

Could you please implement the reflectable package instead? 
You can find it here: 
https://pub.dartlang.org/packages/reflectable

**Comment by stevenroose** [comment]
I know. I have been converting another library from mirrors to reflectable as well. This one probably is next.

**Comment by stevenroose** [comment]
Btw, any additional features that you think might improve this package?

**Comment by bjesuiter** [comment]
Ah, thanks for the fast answer!
I haven't thought of additional features yet. But I'll have a look on the
project where I used your package, maybe I'll get some good ideas :-)

One thing I tried was to remove the need for repeating the valueOf method
inside the extended class,but I wasn't successful yet.

Steven Roose notifications@github.com schrieb am Fr., 1. Apr. 2016, 13:20:

**Comment by jodinathan** [comment]
would be nice if this used reflectable =]

**Comment by stevenroose** [comment]
Actually. With the configurable imports feature being accepted in the newest developer version of Dart and probably in production soon, it should be able to make this accept both mirrors and acceptable. 

Then together with https://github.com/dart-lang/sdk/issues/27759, you would be able to use reflectable with both Flutter and dart2js when you want to and just fall back to mirrors in the VM.

I'll try to implement the change in a separate branch to play with until configurable imports land in stable!

**Comment by ramsestom** [comment]
So. Is the reflectable version of this lib still planned?

**Comment by bjesuiter** [comment]
Since I don't use dart anymore, this issue is non-relevant to me anymore. If anyone still needs this, please open a followup ticket.
